[[transforms.route_by_product.routes]]
name = "product_a"
condition = '.product == "a"'

[[transforms.normalize-router.routes]]
name = "product_a"
condition = '.source == "a"'

[transforms.product-a]
type = "remap"
inputs = ["route_by_product.product_a"]
source = '''
.source = "a"
'''
